# Generated by Django 2.0.7 on 2018-07-31 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('full_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('code', models.CharField(blank=True, max_length=200, unique=True)),
            ],
        ),
    ]
