# Generated by Django 2.0.7 on 2018-07-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlentry',
            options={'verbose_name': 'URL entry', 'verbose_name_plural': 'URL entries'},
        ),
        migrations.RemoveField(
            model_name='urlentry',
            name='id',
        ),
        migrations.AlterField(
            model_name='urlentry',
            name='code',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
